[insert]
path = "insert.txt"

[dump]
path = "dump.txt"
file_params = ["file"]

[head]
path = "head.heml"
text_params = ["title", "meta-desc"]
file_params = ["css"]

[base]
path = "base.heml"
text_params = ["title", "css", "meta-desc"]

[unity]
path = "unity.html"
text_params = ["proj", "width", "height"]

[algiers]
path = "algiers.html"
text_params = ["proj"]

[godot]
path = "godot.html"
text_params = ["proj", "width", "height"]

[wsp]
path = "wsp.html"
text_params = ["proj", "num-pages"]