meta.template = "none"
meta.has_subs = true

data.index_dir = "home.html"

    [s.projects]
    meta.template = "none"
    meta.has_subs = true

    data.index_dir = "projects.html"

        [s.projects.s.flappy-bird]
        meta.template = "game"
        meta.listing = "game"
        meta.has_subs = false

        data.title = "Flappy Bird"
        data.summary = """flap flap flap flap shit."""
        data.intro = """\
        This is the second in a series of games Lorem ipsum dolor sit amet, consectetur adipiscing elit,\
        sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\
        quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure\
        dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur\
        sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."""
        data.width = "1080"
        data.height = "675"
        data.tags = ["Game Development", "Unity"]

        [s.projects.s.pong]
        meta.template = "game"
        meta.listing = "game"
        meta.has_subs = false

        data.title = "Pong"
        data.intro = """\
        This is the first in a series of games Gorem dipsum dolor sit amet,\
        consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.\
        Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\
        consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat\
        nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserun\
        mollit anim id est laborum."""
        data.summary = "The world's first videogame is a good place to start."
        data.width = "1024"
        data.height = "576"
        data.tags = ["Game Development", "Unity"]

        [s.projects.s.measuring-spoons]
        meta.path = "measuring-spoons"
        meta.template = "blog"
        meta.listing = "entry"
        meta.has_subs = false

        data.doc_dir = "measuring-spoons.html"
        data.title = "Measuring Spoons"
        data.summary = """\
        The recipe calls for one fourth of a teaspoon of salt, but all you have is a 1/2 tsp spoon. \
        What do you do?"""
        data.tags = ["Math"]

        [s.projects.s.dancing]
        meta.path = "dancing"
        meta.template = "music"
        meta.listing = "entry"
        meta.has_subs = false

        data.title = "Dancing"
        data.heading = "Dancing (From <i>Hello, Dolly!</i>) [Duet]"
        data.intro = """\
        This might be my favorite arrangement I've made. Hello, Dolly! is my favorite musical and it was so fun to try and fit all\
        the musical brilliance and joy that's happening in the song into two lines two clarinets can play. Maybe I'll do the whole song one\
        day, but for now, the piece starts with the dance break after the vocals are done, includes the first few choruses, and then skips to\
        the end."""
        data.summary = "Hello, Dolly!"
        data.youtube = "https://www.youtube.com/embed/NKoB4U1-Zpo"
        data.tags = ["Music", "Duet"]

        [s.projects.s.he-is-they-are]
        meta.path = "he-is-they-are"
        meta.template = "music"
        meta.listing = "entry"
        meta.has_subs = false

        data.title = "He Is, They Are"
        data.heading = "He Is, They Are"
        data.intro = """/
        A great track from Harry Connick, Jr's album <i>Blue Light, Red Light</i>./
        I transcribed the melody as well as Leroy Jones's amazing trumpet solo."""
        data.summary = "Harry Connick, Jr"
        data.youtube = "https://www.youtube.com/embed/YuzEs_Yo1W8"
        data.tags = ["Music", "Solo"]