meta.template = "none"
meta.has_subs = true

data.index_dir = "home.html"

    [s.projects]
    meta.template = "none"
    meta.has_subs = true

    data.index_dir = "projects.html"

        [s.projects.s.flappy-bird]
        meta.template = "unity"
        meta.listing = "game"
        meta.has_subs = true

        data.title = "Flappy Bird"
        data.summary = "Remember Flappy Bird? I made it in Unity."
        data.intro = """This is the second in a series of games inspired by Harvard's CS50G course. 
        The focus here was on the concept of state (check out that pause button), as well as implementing the classic 
        infinite runner style game."""
        data.controls = "Press space or up to flap."
        data.width = "69.12"
        data.height = "43.2"
        data.tags = ["Game Development", "Unity"]
        data.date = "04/02/2021"

            [s.projects.s.flappy-bird.s.notes]
            meta.template = "game-notes"
            meta.has_subs = false

            data.doc_dir = "blog-docs/flappy-notes.html"
            data.title = "Flappy Bird"

        [s.projects.s.pong]
        meta.template = "unity"
        meta.listing = "game"
        meta.has_subs = true

        data.title = "Pong"
        data.intro = """This is the first in a series of games inspired by Harvard's CS50G course. 
        This was my first real stab at trying something in Unity so I thought I'd start with the basics."""
        data.summary = "The world's first videogame is a good place to start."
        data.controls = "Use the W and S to move Player 1 up and down and use the up and down arrows for Player 2."
        data.width = "71.68"
        data.height = "40.32"
        data.tags = ["Game Development", "Unity"]
        data.date = "03/24/2021"

            [s.projects.s.pong.s.notes]
            meta.template = "game-notes"
            meta.has_subs = false

            data.doc_dir = "blog-docs/pong-notes.html"
            data.title = "Pong"

        [s.projects.s.measuring-spoons]
        meta.template = "blog"
        meta.listing = "entry"
        meta.has_subs = false

        data.doc_dir = "blog-docs/measuring-spoons.html"
        data.title = "Measuring Spoons"
        data.summary = """The recipe calls for one fourth of a teaspoon of salt, but all you have is a 1/2 tsp spoon. 
        What do you do?"""
        data.tags = ["Math"]
        data.date = "03/25/2021"

        [s.projects.s.dancing]
        meta.template = "music"
        meta.listing = "entry"
        meta.has_subs = false

        data.title = "Dancing"
        data.heading = "Dancing (From <i>Hello, Dolly!</i>)"
        data.intro = """This was a really fun arrangement to make. <i class="anti">Hello, Dolly!</i> is my favorite musical and it was so fun to try and fit all 
        the musical brilliance and joy that's happening in the song into just two lines clarinets can play. Maybe I'll do the whole song one 
        day, but for now, the piece starts with the dance break after the vocals, includes the first few choruses, and then skips to 
        the end."""
        data.pagesJSON = "scoreJSON/dancing.json"
        data.numPages = "4"
        data.summary = "The wonderful, whirling waltz from <i>Hello, Dolly!</i> as a duet for clarinets."
        data.tags = ["Music", "Duet"]
        data.date = "03/30/2021"

        [s.projects.s.he-is-they-are]
        meta.template = "music"
        meta.listing = "entry"
        meta.has_subs = false

        data.title = "He Is, They Are"
        data.heading = "He Is, They Are"
        data.intro = """A great track from Harry Connick, Jr's album Blue Light, Red Light. 
        I transcribed the melody as well as Leroy Jones's amazing trumpet solo."""
        data.pagesJSON = "scoreJSON/he-is-they-are.json"
        data.numPages = "2"
        data.summary = "Melody and solo from a Harry Connick, Jr balad."
        data.tags = ["Music", "Solo"]
        data.date = "03/29/2021"

        [s.projects.s.latex2svg]
        meta.template = "blog"
        meta.listing = "hub"
        meta.has_subs = false

        data.doc_dir = "blog-docs/latex2svg.html"
        data.title = "LaTeX2Svg"
        data.summary = "I wanted to display Latex equations with my own locally hosted SVG images, so I made this."
        data.tags = ["Programming"]
        data.date = "04/01/2021"

        [s.projects.s.website]
        meta.template = "blog"
        meta.listing = "hub"
        meta.has_subs = false

        data.doc_dir = "blog-docs/website.html"
        data.title = "Website"
        data.summary = "It's where you're at right now."
        data.tags = ["Programming"]
        data.date = "04/05/2021"

        [s.projects.s.a-lovely-night]
        meta.template = "music"
        meta.listing = "entry"
        meta.has_subs = false

        data.title = "A Lovely Night"
        data.heading = "A Lovely Night (From <i>La La Land</i>)"
        data.intro = """I think this is my favorite of the arrangement's I've made so far. I really love this song and a big 
        part of why is the dynamic between the characters. So I tried to keep some space between the lines and to preserve 
        that sort of friendly-competition feel established in the vocals. I imagine that's easier to do if the lines are played 
        by different instruments, but it was also fun to try and play with a personality distinct from my duet partner 
        even as we were both playing clarinet."""
        data.pagesJSON = "scoreJSON/a-lovely-night.json"
        data.numPages = "4"
        data.summary = "I made the duet from La La Land even duet-ier."
        data.tags = ["Music", "Duet"]
        data.date = "04/06/2021"

        [s.projects.s.breakout]
        meta.template = "unity"
        meta.listing = "game"
        meta.has_subs = true

        data.title = "Breakout"
        data.intro = """This is the third (and last) in a series of games inspired by Harvard's CS50G course. 
        I think it represents a lot of progress from where I started with Pong, both in terms of gameplay and development principles."""
        data.summary = "Break ... all the bricks."
        data.controls = "Use the arrow keys to aim the ball and move the paddle side to side. Use spacebar to serve."
        data.width = "71.68"
        data.height = "40.32"
        data.tags = ["Game Development", "Unity"]
        data.date = "05/26/2021"

            [s.projects.s.breakout.s.notes]
            meta.template = "game-notes"
            meta.has_subs = false

            data.doc_dir = "blog-docs/breakout-notes.html"
            data.title = "Breakout"

        [s.projects.s.a-night-in-algiers]
        meta.template = "algiers"
        meta.listing = "game"
        meta.has_subs = "true"

        data.title = "A Night in Algiers"
        data.intro = """I originally made this game inspired by <i class="anti">The Stranger</i> in high school, but it didn't work so well and I've wanted to 
        revisit it ever since. I finally got around to it, and I ended up making a pretty neat tool for writing parser-based 
        interactive fiction with C# in the process."""
        data.summary = "A text-adventure creative thesis on Albert Camus' <i>The Stranger</i> written with my home-made C# interactive fiction system."
        data.tags = ["Game Development", "Algiers"]
        data.date = "06/30/2021"

            [s.projects.s.a-night-in-algiers.s.notes]
            meta.template = "game-notes"
            meta.has_subs = false

            data.doc_dir = "blog-docs/algiers-notes.html"
            data.title = "A Night in Algiers"
        
        [s.projects.s.breakout-redux]
        meta.template = "godot"
        meta.listing = "game"
        meta.has_subs = true

        data.title = "Breakout Redux"
        data.intro = """I've wanted to try out Godot for a while now, so I decided to remake my latest project, Breakout, with it. Most 
        of what I've learned with Unity carried over, and I'm excited to keep working with this awesome open-source editor."""
        data.summary = "The same game, but in Godot."
        data.controls = "Use the arrow keys to aim the ball and move the paddle side to side. Use spacebar to serve."
        data.width = "71.68"
        data.height = "40.32"
        data.tags = ["Game Development", "Godot"]
        data.date = "11/11/2021"

            [s.projects.s.breakout-redux.s.notes]
            meta.template = "game-notes"
            meta.has_subs = false

            data.doc_dir = "blog-docs/breakout-redux-notes.html"
            data.title = "Breakout Redux"

        [s.projects.s.aoc21]
        meta.template = "blog"
        meta.listing = "hub"
        meta.has_subs = false

        data.doc_dir = "blog-docs/aoc21.html"
        data.title = "Advent of Code 2021"
        data.summary = "My first Advent of Code! I got all the stars and it was a lot of fun."
        data.tags = ["Programming"]
        data.date = "12/30/2021"

        [s.projects.s.session21]
        meta.template = "algiers"
        meta.listing = "game"
        meta.has_subs = true

        data.title = "Session21"
        data.intro = """Ever since I finished A Night in Algiers I've wanted to add features to create a tool capable of bringing much 
        bigger text adventures to life. The result is a new and improved Algiers 2.0, which I used to create a little showcase game 
        centered around a playing blackjack in a saloon. Then I started watching Cowboy Bebop in the middle of development and it 
        became a space-noir tale of action, mobsters, and revenge. That's just how it goes sometimes."""
        data.summary = "The work, which becomes a new game itself, will be called ... SESSION21"
        data.tags = ["Game Development", "Algiers"]
        data.date = "02/17/2022"

            [s.projects.s.session21.s.notes]
            meta.template = "game-notes"
            meta.has_subs = false

            data.doc_dir = "blog-docs/session21-notes.html"
            data.title = "Session21"
        
        [s.projects.s.make-em-laugh]
        meta.template = "music"
        meta.listing = "entry"
        meta.has_subs = false

        data.title = "Make 'Em Laugh"
        data.heading = "Make 'Em Laugh (From <i>Singin' in the Rain</i>)"
        data.intro = """This arrangement (and one for Moses, which is on-deck) has been lying around half-finished for some time 
        and I thought it was about time I finished it up. It's a fun song and I think it ended up fun to play. Special mentions go to measure 
        25's impossible fingering and the surprisingly smooth riff at measure 55."""
        data.pagesJSON = "scoreJSON/make-em-laugh.json"
        data.numPages = "4"

        data.summary = "In the words of that immortal bard, Samuel J. Snodgrass, as he was about to be lead to the guillotine..."
        data.tags = ["Music", "Duet"]
        data.date = "03/10/2022"

        [s.projects.s.webscore-player]
        meta.template = "blog"
        meta.listing = "hub"
        meta.has_subs = false

        data.doc_dir = "blog-docs/webscore-player.html"
        data.title = "Webscore Player"
        data.summary = "Play MuseScore projects in your web browser."
        data.tags = ["Programming", "Music"]
        data.date = "03/21/2022"

    [s.contact]
    meta.template = "none"
    meta.has_subs = false

    data.index_dir = "contact.html"

    # [s.secrets]
    # meta.template = "none"
    # meta.has_subs = true

    # data.index_dir = "secrets.html"