[file-plop]
path = "plop.txt"
file_params = ["file"]

[head]
path = "head.html"
text_params = ["title"]
file_params = ["css"]

[base]
path = "base.html"
text_params = ["title", "css", "inner", "inner-params"]