title = "Dancing"
heading = "Dancing (From <i>Hello, Dolly!</i>) [Duet]"
intro = """ This might be my favorite arrangement I've made. Hello, Dolly! is my favorite musical and it was so fun to try and fit all
            the musical brilliance and joy that's happening in the song into two lines two clarinets can play. Maybe I'll do the whole song one
            day, but for now, the piece starts with the dance break after the vocals are done, includes the first few choruses, and then skips to
            the end.
            """
summary = "Hello, Dolly!"
youtube = "https://www.youtube.com/embed/NKoB4U1-Zpo"