title = "He Is, They Are"
heading = "He Is, They Are"
intro = """ A great track from Harry Connick, Jr's album <i>Blue Light, Red Light</i>.
            I transcribed the melody as well as Leroy Jones's amazing trumpet solo."""
summary = "Harry Connick, Jr"
youtube = "https://www.youtube.com/embed/YuzEs_Yo1W8"